
# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: adoagent
  demands:
    - Agent.name -equals ip-172-31-93-85

stages:
  - stage: RunTests
    jobs:
      - job: RunTests
        workspace:
          clean: all
        steps:
          - checkout: self
          - script: |
              sudo apt install -y python3-pytest python3-pytest-django
              cd mysite/mysite
              pytest
            displayName: 'Run Tests'
  - stage: DeployApplication
    jobs:
      - job: DeployApplication
        workspace:
          clean: all
        steps:
          - checkout: self
          - script: |
              systemctl stop flashcardapp.service
              rm -rf /opt/flashcardapp/*
              cp -r mysite/* /opt/flashcardapp/
              chmod -R 750 /opt/flashcardapp
              chown -R flashcardapp:flashcardapp /opt/flashcardapp
              systemctl start flashcardapp.service
              systemctl status flashcardapp.service
            displayName: 'Deploy Application'

